[project]
name = "selleros"
version = "0.1.0"
description = ""
authors = [
    {name = "GautamGirdhar",email = "girdhargautam6@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django (>=5.2,<5.3)",
    "django-ninja (>=1.6.2,<2.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "pillow (>=12.3.0,<13.0.0)",
    "psycopg[binary] (>=3.3.4,<4.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "pydantic[email] (>=2.13.4,<3.0.0)",
    "google-auth (>=2.56.2,<3.0.0)",
    "requests (>=2.34.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
